### ISSUE TITLE
还不实用

### ISSUE THREAD

**Issue by ysqopen** [nzbin/Framework7-CityPicker#2]
你的这个根本达不到实用。是学习用的吧？
1.没有初始化的值
2.不能多个实例
3.地区数据旧，地区排序也没对。
4.为了达成实际的应用，还要加上取消功能。

我改了，地区数据我改到了87.9K，数据结构也简单，因为只有一种结构。性能不会差。
不过，framework7.js本身上百k了。最新版的4.7，有300多k。所以地区数据再小也没多大意义。

初始化数据和取消功能，非常之不好搞。
我写了全部整整370多行（加上注释）才搞好。
忍不住要吐槽下。

**Comment by nzbin** [comment]
感谢反馈，因精力有限，该项目未做进一步优化，其实可以改造一下，移除 Framework7

**Comment by ysqopen** [comment]
framework7是自成一套的架构，有排它的问题，对其它架构很有影响。
为此时不时出现不可解决的问题。
所以，framework7看似简单，真用起来很折磨人。

**Comment by nzbin** [comment]
这个项目就是为 Framwork7 开发的，结合 F7 开发移动端项目还是不错的
